version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=jkopadmin
      - RABBITMQ_DEFAULT_PASS=jkoppassword
    ports:
      - "5672:5672"
      - "15672:15672"
